name: Upload PAC FIle To Azure Blob Storage
on:
  workflow_dispatch:
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: PAC
          container_name: ghtest
          connection_string: ${{ secrets.ConnectionString }}
          extra_args: '--pattern *.pac'
          # WARNING: this will overwrite existing blobs in your blob storage
          overwrite: 'true'